import { UserProvider } from "@/utilities/UserContext";
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sign in",
  description: "Generated by create next app",
};

export default function SigninLayout({ children }) {
  return (
    <html>
      <body style={{ margin: 0 }}>
        <UserProvider>
          <main>{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
