import { UserProvider } from "@/utilities/UserContext";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});
export const metadata = {
  title: "Sign in",
  description: "Generated by create next app",
};

export default function SigninLayout({ children }) {
  return (
    <html>
      <body style={{ margin: 0 }} className={roboto.className}>
        <UserProvider>
          <main>{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
