import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function RegisterLayout({ children }) {
  return (
    <html>
      <body style={{ margin: 0 }}>
        <main>{children}</main>
      </body>
    </html>
  );
}
