import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});
export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function RegisterLayout({ children }) {
  return (
    <html>
      <body style={{ margin: 0 }} className={roboto.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
